# 使用 Python 官方映像檔作為基底
FROM python:3.10.12-slim
# FROM tiangolo/uvicorn-gunicorn-fastapi:python3.10-slim

# 設定工作目錄
WORKDIR /app

# 將本地端的程式碼複製到 Docker 映像檔中
COPY . .


# RUN apt-get install build-dep python-psycopg2

# 安裝 Python 套件
# For Basis
RUN pip install fastapi 'uvicorn[standard]'
RUN pip install scalar-fastapi

# For Auth
RUN pip install "python-jose[cryptography]"
RUN pip install "passlib[bcrypt]"

# For DB
RUN pip install sqlmodel
RUN pip install psycopg2-binary
RUN pip install bson

# 指定容器啟動時要執行的指令
CMD ["python", "main.py"]

# source ./.venv/bin/activate
# pip freeze > requirements.txt
# pip uninstall -r requirements.txt -y